config/routes.rb
Rails.application.routes.draw do
  get 'merge_issues/select/:issue_a_id', to: 'merge_issues#select_issue', as: 'select_merge_issue'
  post 'merge_issues', to: 'merge_issues#merge'
end

app/controllers/merge_issues_controller.rb
class MergeIssuesController < ApplicationController
  # before_action :authorize

  def select_issue
    @issue_a = Issue.find(params[:issue_a_id])
    @issues = Issue.where(project_id: @issue_a.project_id).where.not(id: @issue_a.id)
  end

  def merge
    @issue_a = Issue.find(params[:issue_a_id])
    
    if params[:issue_b_id]
      @issue_b = Issue.find(params[:issue_b_id])

      if @issue_b
        MergeService.new(@issue_a, @issue_b).merge!
        flash[:notice] = t('label_merge_success', obj: [@issue_a.id, @issue_b.id].join(', '))
      else
        flash[:alert] = t('error_label_not_found')
      end
    else
      flash[:alert] = t('error_missing_issue_b_id')
    end

    redirect_to issue_path(@issue_a)
  end

end

app/views/merge_issues/_merge_button.html.erb
<% if User.current.allowed_to?(:merge_issues, @project) %>
  <%= link_to l(:label_merge_issues), select_merge_issue_path(issue_a_id: @issue.id),class: 'btn btn-primary' %>
<% end %>

app/views/merge_issues/select_issue.html.erb
<h1><%= l(:label_title_merge) %></h1>

<%= form_with url: merge_issues_path, method: :post do %>
  <div>
    <label for="issue_b_id"> <%= l(:label_choose_dialog) %> </label>
    <%= select_tag 'issue_b_id', options_from_collection_for_select(@issues, :id, :subject) %>
    <%= hidden_field_tag 'issue_a_id', @issue_a.id %>
  </div>
  <%= submit_tag t('label_merge_issues') %>
<% end %>

<%= link_to t('cancel_merge'), issue_path(@issue_a) %>